language: java

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk10

before_script:
  - ./gradlew assemble

script:
  - ./gradlew test -i
  - ./gradlew build
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
